import Footer from '@/components/footer'
import Header from '@/components/header'
import Providers from '@/components/providers'
import type { Metadata } from 'next'
import React from 'react'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='fa' dir={'rtl'} suppressHydrationWarning>
			<body className='antialiased flex flex-col min-h-dvh'>
				<Providers>
					<Header />
					<main className='flex-1'>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
